[tool.poetry]
name = "metalyzr-backend"
version = "0.1.0"
description = "Metalyzr backend: FastAPI, Scrapy, PostgreSQL, Redis"
authors = ["Metalyzr Team <contact@metalyzr.gg>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
# Backend
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
python-multipart = "^0.0.9"
slowapi = "^0.1.9"

# Database
psycopg2-binary = "^2.9.9"
sqlalchemy = "^2.0.29"
alembic = "^1.13.1"

# Data Processing
pandas = "^2.2.2"
pyarrow = "^16.1.0"

# Scraping
scrapy = "^2.11.2"
beautifulsoup4 = "^4.12.3"
selenium = "^4.21.0"
lxml = "^5.2.2"

# Redis
redis = "^5.0.4"

# Observability
prometheus-client = "^0.20.0"
psutil = "^5.9.8"

# Other
python-dotenv = "^1.0.1"
aiofiles = "^23.2.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"
pytest-cov = "^5.0.0"
ruff = "^0.4.4"
pre-commit = "^3.7.0"
httpx = "^0.27.0" # For testing FastAPI

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 