global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "metalyzr_rules.yml"

scrape_configs:
  # Métriques de l'API Metalyzr
  - job_name: 'metalyzr-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Métriques système
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Auto-monitoring Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Redis métriques (si redis_exporter ajouté)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: [] 